### ISSUE TITLE
No saved history

### ISSUE THREAD

**Issue by AckslD** [isamert/scli#104]
Even if I set `save-history = true` in `sclirc` it does not seem to work. A file is created at `~/.local/share/scli/history` but it only contains:
```
{"envelopes": [], "notify_counts": {}, "delivery_status": {}}
```
even after receiving a bunch of messages

**Comment by exquo** [comment]
Strange, seems to work on my side.

I've removed my current `~/.local/share/scli/history` and replaced `~/.config/sclirc` with one with a single line `save-history = true`. Started `scli` without any `--argument`s, sent a message to myself. Then closed scli (with either `:q` or `Ctrl + C`). The message and its delivery status were in the history file. I've also tried it with receiving instead of sending.
This is on current `master`.

Could you try this and report back if it does not work?

**Comment by AckslD** [comment]
Sorry, I must have made something wrong it does indeed work now :)
