### ISSUE TITLE
Wrong categorisation of groups

### ISSUE THREAD

**Issue by AckslD** [isamert/scli#123]
When opening newest version of scli it happened that some individual contacts, which I had new messages from, ended up in the "Groups"-section. Only happened to contacts with new messages. Closing and starting scli again fixed the issue (probably cause there were they no new messages then). I wonder if it can be related to #121 since there is a check if [`not g.get("name")`](https://github.com/isamert/scli/blob/master/scli#L890) when deciding if a chat is a group or not.

**Comment by exquo** [comment]
Thanks for reporting! I was able to reproduce this if the contacts list is filtered (the search is on). This is similar to #101. The problem is in [`ContactsListWidget._move_contact_top()`](https://github.com/isamert/scli/blob/master/scli#L2241): it moves the widget in the search results, but not in the 'pre-filter' contents.
