### ISSUE TITLE
Support for wl-clipboard?

### ISSUE THREAD

**Issue by Plaane** [isamert/scli#150]
Is it possible to add support for wl-clipboard for those on wayland?

**Comment by exquo** [comment]
Yes, scli allows to specify custom clipboard commands instead of the default `xclip`. To copy the contents of messages to clipboard (with the `y` key in scli), try the following:

	scli --clipboard-put-command='wl-copy %s' 

To attach the contents of the files in the clipboard with the `:attachClip` command, use the `--clipboard-get-command='wl-paste …'`. The command in quotes should return a list of files to be attached.

From `scli -h`:

	-G CLIPBOARD_GET_COMMAND, --clipboard-get-command CLIPBOARD_GET_COMMAND
			Command used by `:attachClip` to get a list of files
			to send as attachments. Should return one absolute
			file path per line. If not set, `xclip` is used.
	-P CLIPBOARD_PUT_COMMAND, --clipboard-put-command CLIPBOARD_PUT_COMMAND
			Command to put text on clipboard. %s will be replaced
			with the text. If not set, `xclip` is used.
