### ISSUE TITLE
Contacts' names

### ISSUE THREAD

**Issue by mark2185** [isamert/scli#186]
How can I show the contact's names from my original device (from the contact list/phonebook) instead of the nicknames/usernames they write for themselves?

I swear the names changed after my last restart of `scli`...

**Comment by maximbaz** [comment]
You are not imagining it, I also noticed that names keep changing, sometimes I see users' self-chosen alias like `johny`, other times it changes to name as in official signal apps (guess from my phonebook?) like `John Smith`, and other times it even changes to format `+123456789 ~johny`. I just never got around to ask/report about it, and I have a suspicion the issue is actually inside signal-cli 🙂

**Comment by exquo** [comment]
I have seen this too. Don't know what exactly causes it, but it seems to be related to when the main device is offline (while signal-cli is probably requesting contacts info from the servers).

> I have a suspicion the issue is actually inside signal-cli

Yes, scli gets the contacts data from signal-cli's `recepients-store` in `~/.local/share/signal-cli/data/+YOUR_PHONE_NUM.d/recipients-store`. The contacts' names there is what scli uses.

> How can I show the contact's names from my original device

Try syncing your contacts with the main device. 
On signal-android: tap the "new message" (pencil icon in lower right) -> three dots in top right -> Refresh. (Or pull the contacts list down to refresh).
You can also request contacts sync using signal-cli's `sendSyncRequest` command (see the man page for details). The master device needs to be online for this to work.

**Comment by mark2185** [comment]
> On signal-android: tap the "new message" (pencil icon in lower right) -> three dots in top right -> Refresh. (Or pull the contacts list down to refresh).

That did it! Thanks!

I guess this can be closed since it's not `scli`'s fault.
