### ISSUE TITLE
Config option to set margin between messages

### ISSUE THREAD

**Issue by meZeex** [isamert/scli#211]
For me, all the messages being together without having some sort of spacing between, makes it hard to keep track of where they begin and end

It would be nice, to have an option, for example --message-spacing, to set a given amount of space between every message

I don't know how curses interfaces work, so maybe it can just be a number telling the amount of empty lines between messages

Alternatively there could be something visually separating the messages, but i feel this might mess with the UI

**Comment by exquo** [comment]
I was considering adding some general formatting option, allowing users to specify the layout of each message with e.g. a "format string". A more general approach to https://github.com/isamert/scli/discussions/167.    

Since this is a terminal app, the vertical margins can only be multiples of full lines.. Most users seem to prefer a denser layout; so they would hate to sacrifice an extra line for every message. But, ideally everyone would be able to customize the looks to their own tastes.

In the meantime, you can try to use a `--show-names`, I think it could provide the kind of visual breaks you have in mind.

**Comment by meZeex** [comment]
yes, it clearly needs to be an individual setting, so everyone can choose themselves

but i thing just one line of margin would be really nice to have a better overview of messages

the --show-names option doesn't really do it (at least for me)
