### ISSUE TITLE
"Linking Device Failed"

### ISSUE THREAD

**Issue by ventz** [isamert/scli#3]
Hi,

Followed steps to getting the `tsdevice:/?uuid=...&pub_key=...`

Used `qrencode '$output-abve' -o qrcode.png`

After scanning it, I am getting:

```
Linking Device Failed
Request failed: not found (404)
```

Have you run into this before? I have tried a few times, and same result.

**Comment by isamert** [comment]
Are you getting this error from Signal app or `signal-cli` outputs this? Anyway,  I have no idea, maybe double check your internet connection on both sides? Also it's probably just a typo but in case you typed the `tsdevice://` part by hand, it should have only one `/`, so that `tsdevice:/...`.

**Comment by ventz** [comment]
@isamert It's from the signal phone app while scanning the the qr image.

Both sides have unproxied/unfiltered internet (I have also linked other devices -- ex: chrome extension), so I don't believe that's the issue.

I copied and pasted the `tsdevice:/` when generating the qr code (the typo was only above in the github issue).

Asked a couple of friends to try this -- they are all running into the same problem. This is using the latest release of signal-cli.

**Comment by isamert** [comment]
I tried to re-link my device and I did it successfully. If you want to investigate further, try to re-link your chrome extension and see if it works? (But beware that you may also loose that device if the problem is related to signal, rather than `signal-cli`.) Then I suggest you to report the issue to signal-cli or signal app depending on the result.

**Comment by ventz** [comment]
@isamert Re-linked chrome extension - works.

Thanks. I'll reach out to signal-cli's developer -- sorry, for some reason I thought signal-cli was also your project.

**Comment by isamert** [comment]
Hope it gets fixed! Just leaving this here for future reference: AsamK/signal-cli#190

**Comment by ventz** [comment]
@isamert Thanks. I'll also update here once there's more info, in case anyone runs into the same/ends up here.

**Comment by ventz** [comment]
@isamert Never heard back from AsamK, but after some stracing and network monitoring, I discovered the answer myself - it looks like when you run the `link`, and get the tsdevice output, after copying it, you can't "end" the command to run the qrcode in the same terminal -- that is, you need to leave it backgrounded (or running in another window) -- so that you can have it "receive" the link request. This was what was causing the problem. This was not clear from the steps -- would you consider updating your read me with something like "the link command must continue to listen in the foreground/background in order to receive the link request" while you go and generate the qrcode.

**Comment by isamert** [comment]
I added some clarification to README. If you think it's still vague or any other part of the README is vague, you can just edit and send a pull request (even for grammatical errors, my English is bit sloppy.). Thanks for tracking it and not just giving up BTW, probably some people just gave up using scli because of this.

**Comment by ventz** [comment]
@isamert Great - Thank you! (and no problem).

I got the client to work, but I ran into this issue:
https://github.com/AsamK/signal-cli/issues/191

I don't believe it's related to your side of things. I tested it on Alpine linux and Ubuntu just to eliminate some basic things.

It seems to happen while receiving down the contacts. I believe it's a real bug.
What happens after that is I see only 4-5 contacts (out of hundreds) and the group chats. Sending messages to the available contacts doesn't end up sending to them, and it doesn't display on the screen.

**Comment by ventz** [comment]
@isamert Looks like AsamK fixed the other bug too:
https://github.com/AsamK/signal-cli/issues/191

Everything now opens and loads. The one issue I am noticing is that sending messages (after everything is linked, contacts/groups are loaded, etc), does not end up sending or displaying the msg for some reason. I'll open a new issue for this.

**Comment by rikhuijzer** [comment]
I just had this problem on multiple computers too when trying to connect via `scli` and `signal-cli`; always with the same iPhone. The problem got resolved when I unlinked and re-linked the offical Signal Desktop on Linux; apart from that I didn't change a thing. It could be that the server or my phone app ended up in a bad state for some reason which was fixed by using the official Desktop app
