### ISSUE TITLE
utf-16 characters not working

### ISSUE THREAD

**Issue by KarukSophia** [isamert/scli#33]
Hi, as a Dane I use the characters æøå a lot for writing with my friends, but these characters show up as question marks. I've tried changing all references in the source code from "utf-8" to "utf-16", but that didn't work. Is there a way to get utf-16 characters in the TUI?

**Comment by isamert** [comment]
Can you write your terminal emulators name and which font does it use? It's probably either a font issue or a terminal emulator issue because I'm not having any trouble with those characters. It's likely that the monospace font that your terminal uses does not have those characters. You can experiment with different font/terminal emulator combos.

**Comment by KarukSophia** [comment]
My terminal emulator name is 'Konsole' and the font that it uses is 'Hack'. Out of curiosity, what are you using?

**Comment by isamert** [comment]
![image](https://user-images.githubusercontent.com/8031017/68400975-fe7d6700-0189-11ea-8634-bf1ef664f7ad.png)
Sending also works for me (although I just copy-pasted text from here, can't test inputting from keyboard).

I'm using a [patched version of st](https://github.com/isamert/st), with _Iosevka_ font.

I will try to test Konsole when I find some free time.

**Comment by KarukSophia** [comment]
Thank you
