### ISSUE TITLE
Fails to launch with KeyError: 'active'

### ISSUE THREAD

**Issue by jthvai** [isamert/scli#53]
As the title says, `scli` fails to launch with the following output:
```
Traceback (most recent call last):
  File "/usr/bin/scli", line 1656, in <module>
    main()
  File "/usr/bin/scli", line 1640, in main
    window = MainWindow(state)
  File "/usr/bin/scli", line 1157, in __init__
    self._wleft = LeftWindow(self.state)
  File "/usr/bin/scli", line 907, in __init__
    self._wcontacts = ContactsWindow(self.state)
  File "/usr/bin/scli", line 793, in __init__
    self.set_contacts(self.state.signal.get_all_contacts())
  File "/usr/bin/scli", line 771, in get_all_contacts
    xs.extend(self.groups())
  File "/usr/bin/scli", line 754, in groups
    return list(filter(lambda a: bool(a['active']),
  File "/usr/bin/scli", line 754, in <lambda>
    return list(filter(lambda a: bool(a['active']),
KeyError: 'active'
```
OS: Arch Linux (Updated), ~~running [this version of scli from the AUR](https://aur.archlinux.org/packages/scli-git/)~~.

**Comment by galmio** [comment]
I had the same problem. It seems that signal cli's json file stored in `~/.local/share/signal-cli/data/{phone_no}` does not return an `active` property for the `["groupStore"]["groups"]` object anymore. I fixed it by only filtering the groups with the `name` property. In line 754 of `/usr/bin/scli`
```python
return list(filter(lambda n: bool(n['name']), self._data['groupStore']['groups]))
```

Also, groups did not return the correct member names, fixed it in line 1065 with 
```python
num = ', ' . join([get_contact_name(self.state.signal.get_contact(contact['number'])) for contact in contact['members']])
```

**Comment by isamert** [comment]
This happens because scli does not support `signal-cli 0.6.7` yet.

@galmio I tried your fix but it brokes `scli` for me, even for `signal-cli 0.6.7`. Can you share how your `~/.local/share/signal-cli/data/+YOUR_PHONE_NUMBER`, especially the `groupStore` part (Don't forget to remove personal information). For example, mine looks like this:

(for `signal-cli 0.6.5`)
```
  "groupStore" : {
    "groups" : [ {
      "groupId" : "---------",
      "name" : "---------",
      "members" : ["+90......", "+90......"],
      "color" : "blue",
      "active" : true
    }, {
      "groupId" : "---------",
      "name" : "---------",
      "members" : ["+90......", "+90......"],
      "color" : "blue",
      "active" : true
    }, .... ]
  },
```

(for `signal-cli 0.6.7`)
```
  "groupStore" : {
    "groups" : [ {
      "groupId" : "-------",
      "name" : "-------",
      "members" : [ "-------" ],
      "color" : "blue",
      "blocked" : false,
      "inboxPosition" : null,
      "archived" : false,
      "messageExpirationTime" : 0
    }, {
      "groupId" : "-------",
      "name" : "-------",
      "members" : [ "+90......", "+90......" ],
      "color" : "blue",
      "blocked" : false,
      "inboxPosition" : null,
      "archived" : false,
      "messageExpirationTime" : 0
    } ]
  },
```

So your change about the `active` key is correct (also we need to do a filter based on if group is archived or not) but the change about the member name retrieving logic should stay same, at least based on my observation.

**Comment by galmio** [comment]
```json
"groupStore" : {
    "groups" : [ {
      "groupId" : "----------",
      "name" : "--------",
      "members" : [ {
        "uuid" : "--------",
        "number" : "--------"
      }, {
        "uuid" : "--------",
        "number" : "--------"
      }, {
        "uuid" : "--------",
        "number" : "--------"
      }, {
        "uuid" : "--------",
        "number" : "--------"
      } ],
      "color" : "blue",
      "blocked" : false,
      "inboxPosition" : 7,
      "archived" : false,
      "messageExpirationTime" : 0
    }]
  },
```
It looks exactly the same and I'm also using `signal-cli 0.6.7`. Concerning the group member names, previous to applying my fix, all the member names appeared as `NULL` because I believe `number` is representing the whole contact object in
```python
([get_contact_name(self.state.signal.get_contact(number)) for number in contact['members']])
```
when the function `get_contact` takes as parameter a number or id, so I needed to provide the key `number['number']` in order for it to read it. 

Also, something I haven't found in the README is how to get notifications for messages when outside of `scli`, do I need to set up the [system bus for signal-cli](https://github.com/AsamK/signal-cli/wiki/DBus-service)?

**Comment by isamert** [comment]
You need to start `scli` with `--enable-notifications=true` or put this line `enable-notifications=true` to scli config file. (Also you need to have `notify-send` binary installed in your system, that comes with the `libnotify` package or you can change how notifications are sent, using `--notification-command` option, check out `scli --help`.)

The difference between mine and your `groupStore` is that mine only has the numbers, not objects that contains both a `number` and a `uuid`. So what I realized is when you do a fresh install of `signal-cli 0.6.7` it formats `members` just like your example but when you upgrade it from an earlier version it does not re-format, it simply uses the old format. So we need to handle that too. I will roll out a fix.
