### ISSUE TITLE
Receive messages using signal-cli system DBus interface

### ISSUE THREAD

**Issue by facadeproof** [isamert/scli#59]
*Deleted*

**Comment by isamert** [comment]
Unfortunately, scli simply starts the `signal-cli` in daemon mode by itself in json mode, it does not use the DBus interface for retrieving messages. It would be cleaner to use the DBus interface for retrieving messages in terms of implementation but making `signal-cli` work with system DBus requires too much work. Getting your number registered with signal-cli is already too much work and I don't wanna bring another preparation step to users. On the other hand, a graceful solution might be detecting if `signal-cli` is running on system DBus and using it instead of starting a new `signal-cli` daemon in json mode, otherwise simply falling back to json daemon mode.

I'm leaving this as a feature request here. I may look into this but I don't see a real benefit in setting up `signal-cli` system DBus mode for my workflow.

**Comment by galmio** [comment]
I understand your approach, I too agree that setting up the DBus service takes unnecessary effort. However, is it still possible to receive background notifications from scli without it or do I have to implement it myself like in this [example](https://github.com/AsamK/signal-cli/wiki/DBus-service#receive-messages-from-signal-cli-daemon)?

**Comment by isamert** [comment]
Oh, I probably didn't understand what you want. What do you mean by background notifications? `scli` sends notifications whenever a message arrives, if you start it with `--enable-notifications` (or put the relevant setting in the config file, also you need to have `libnotify` to get notifications by default). Also you can change the notification program with `--notification-program`. So for example `scli --notification-program "program '%s' '%m'"` will call `program` with sender name and the message content when a new message arrives. Does these cover what you want?

**Comment by galmio** [comment]
What I'm trying to achieve is not having to start `scli` directly through the CLI in order to start fetching the incoming messages and notify me (what is currently happening now). I'd like to somehow start `scli` as a background process (like a daemon) on startup to be able to send notifications without the program having to be opened. I already have the relevant settings on my `sclirc`

**Comment by isamert** [comment]
So you are only interested in receiving notifications, right? If so, you can simply start scli like `scli &` inside a script that runs at startup, or you can create a systemd unit file that runs `scli`. I'm not quite sure but something like this may work:

```
[Unit]
Description=Run scli as daemon
After=multi-user.target

[Service]
ExecStart=/path/to/scli

[Install]
WantedBy=multi-user.target
```

Put this file as `scli.service` in `~/.config/systemd/user/`. Then `systemctl --user daemon-reload` and `systemctl --user enable scli`.

**Comment by galmio** [comment]
Thanks for the heads up, neither of them work to receive new notifications. The unit file returns
```bash
● scli.service - Run scli as daemon
     Loaded: loaded (/home/user/.config/systemd/user/scli.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2020-05-01 22:11:53 BST; 9min ago
    Process: 140830 ExecStart=/home/user/.local/bin/scli (code=exited, status=1/FAILURE)
   Main PID: 140830 (code=exited, status=1/FAILURE)

May 01 22:11:53 arch scli[140830]:     codes = self._get_gpm_codes() + self._get_keyboard_codes()
May 01 22:11:53 arch scli[140830]:   File "/home/user/.local/lib/python3.8/site-packages/urwid/raw_display.py", line 523, in _get_keyboard_codes
May 01 22:11:53 arch scli[140830]:     code = self._getch_nodelay()
May 01 22:11:53 arch scli[140830]:   File "/home/user/.local/lib/python3.8/site-packages/urwid/raw_display.py", line 661, in _getch_nodelay
May 01 22:11:53 arch scli[140830]:     return self._getch(0)
May 01 22:11:53 arch scli[140830]:   File "/home/user/.local/lib/python3.8/site-packages/urwid/raw_display.py", line 571, in _getch
May 01 22:11:53 arch scli[140830]:     return ord(os.read(fd, 1))
May 01 22:11:53 arch scli[140830]: TypeError: ord() expected a character, but string of length 0 found
May 01 22:11:53 arch systemd[668]: scli.service: Main process exited, code=exited, status=1/FAILURE
May 01 22:11:53 arch systemd[668]: scli.service: Failed with result 'exit-code'.
```
 And running `screen -S scli` or `scli &` does not help either.
