### ISSUE TITLE
Error message when launching scli

### ISSUE THREAD

**Issue by xyz-nobody** [isamert/scli#60]
Hello,

Thank you already for this wonderful initiative.
An alternative to signal-desktop is vital for many users.

I have a signal-cli that works perfectly.

I tried to install on a debian buster (armv7) scli.
I installed libunixsocket-java + pip3 install urwid + pip3 install urwid_readline

And when I launch scli I get this message I don't understand: 

./scli -u +XXXXXXXXXXX

Traceback (most recent call last):
  File "./scli", line 1774, in <module>
    main()
  File "./scli", line 1757, in main
    window = MainWindow(state)
  File "./scli", line 1276, in __init__
    self._wleft = LeftWindow(self.state)
  File "./scli", line 980, in __init__
    self._wcontacts = ContactsWindow(self.state)
  File "./scli", line 866, in __init__
    self.set_contacts(self.state.signal.get_all_contacts())
  File "./scli", line 848, in get_all_contacts
    xs.extend(self.contacts())
  File "./scli", line 822, in contacts
    self._data['contactStore']['contacts'])),
  File "./scli", line 821, in <lambda>
    lambda x: bool(get_contact_name(x).strip(' ')),
  File "./scli", line 175, in get_contact_name
    if name or name.strip(' ') != '':
AttributeError: 'NoneType' object has no attribute 'strip'

What didn't i understand about throwing scli?

Regards

**Comment by HugoForrat** [comment]
Hi, I had the same error and I think it's a bug in scli, not a mistake on your end. I didn't managed to fix the program but there is a workaround : open a the "data file" (don't really know how to call it) generated by `signal-cli`.
This file is usually `$HOME/.local/share/signal-cli/data/<phone_numer>`.

Search for `contactStore`; you should have an array name contacts following this line, with a json object for each contact. One or several of them should have `none` as a name attribute (the line will look like `"name" : none,` ).

Edit the line so that there is a string instead of none (i.e 
`"name" : "first_name last_name",`
).

Save the file and scli should work.

**Comment by exquo** [comment]
This should be fixed in #64. 

Out of curiosity, could anyone affected by this share what kind of contacts have `"name" : null` in signal-cli's data file? (what's special about them?) I don't have any of those.

Btw, thanks @HugoForrat for explaining what causes this problem - I would not have been able to reproduce it without that!

**Comment by HugoForrat** [comment]
Thanks for the fix @exquo.

Regarding the kind of contacts who have `null` as a name in the signal-cli's data file, I think it was contacts who joined group chat I was also part of but that I did not have saved in my phone's contacts. 

But this is just a hunch, I have not reliably proven that this is what causes it, so take it with a grain of salt.

**Comment by exquo** [comment]
@HugoForrat, thanks for the feedback! I'll try to look into it further. If it's really a contact that's in the group chat but not in your phone's contacts, then scli probably should not include it in its contacts list either, just keep it in the group chat. But for now scli at least starts in this situation :)  

On Sun-09:00, HugoForrat wrote:
> Thanks for the fix @exquo.
> 
> Regarding the kind of contacts who have `null` as a name in the signal-cli's data file, I think it was contacts who joined group chat I was also part of but that I did not have saved in my phone's contacts. 
> 
> But this is just a hunch, I have not reliably proven that this is what causes it, so take it with a grain of salt.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/isamert/scli/issues/60#issuecomment-640240326

-------------------------------------------------
This free account was provided by VFEmail.net - report spam to abuse@vfemail.net
 
ONLY AT VFEmail! - Use our Metadata Mitigator to keep your email out of the NSA's hands!
$24.95 ONETIME Lifetime accounts with Privacy Features!  
15GB disk! No bandwidth quotas!
Commercial and Bulk Mail Options!

**Comment by exquo** [comment]
@HugoForrat, 
I've just experimented with being added to a group containing members that are not currently among my contacts, and I can confirm your guess: those contacts are indeed added to scli's (individual) contacts list. I think this is not the desired behavior - I don't need to have all the groups members as my individual contacts. However, at the moment there isn't much that can be done on scli's side: in signal-cli's data file (where scli gets its contacts info) there is no difference between those contacts with empty names that were added automatically from a group chat I'm in and contacts with empty names that I have one-to-one conversations with. Right now, scli can either ignore all contacts with empty names, or list them all. I've opened an ticket upstream (AsamK/signal-cli#328) to introduce some distinction between those two types of nameless contacts.
