### ISSUE TITLE
Allow conversations with non-contacts

### ISSUE THREAD

**Issue by jbg** [isamert/scli#61]
I don't give the Signal app contact access, since Signal shows my conversation partners' chosen nicknames anyway. This works fine with the Signal mobile app and with signal-desktop, but with scli I am unable to converse with anyone since it only displays conversations for contacts.

Perhaps you could consider changing the left pane to show conversations rather than contacts? Or provide some other way to converse with people that are not in the contact list?

**Comment by isamert** [comment]
For an easy solution, I may just go with the latter option. Like getting an input from the user (like phone number) and then scli may add that number to the left pane. Syncing earlier conversations from the phone may be problematic, this one seems like a better option.

**Comment by exquo** [comment]
I've just experimented with exchanging messages with phone numbers that are not in my phone's contacts / address book. The result is that syncing conversations works the same as on signal-desktop (except that scli needs a restart to display those new conversations, but that should be a separate issue, see #71) 

Here's what already works (i.e. after an action below, the "new" contacts' phone numbers are added to signal-cli's data file, loaded by scli at starttime, and are displayed in scli's contacts list):
- Receiving a message from a 'new' number (one not in phone's contacts list and not from an existing prior conversation).
- Being added to a group chat containing (or having exclusively) members with 'new' numbers. 
- Sending a message to a 'new' number from signal-android.
- Ditto from signal-cli.

Functionality that's currently missing in scli:
- Initiating a new conversation with a contact that's not in phone's contacts list. 
- Creating a new group chat.
- Displaying the nickname chosen by the contact alongside / instead of just the phone number for contacts not in phone's address book.

BTW, signal-desktop does not provide the first two functions either.
It should be relatively straightforward to add the first one to scli (mostly a matter of adding the UI): signal-cli can take any phone number as a recipient and will automatically add the new number to its `contactsStore`. The second one is also possible through signal-cli - it has the `updateGroup` command to create new groups. The third does not look possible at the moment - signal-cli does not provide the nicknames information. I have opened a ticket for that in their repo AsamK/signal-cli#327.

I think this issue has not been meant to be about creating new groups, so I have opened a separate issue for that (#72). Then this one can be just about adding the functionality for messaging a new number. (And also for discussing any other required functionality that I haven't thought about)
