### ISSUE TITLE
Support running in daemon mode

### ISSUE THREAD

**Issue by distefam** [isamert/scli#75]
I like running `scli` in the background to receive notifications and maintain a chat history (I know history can be preserved but it is not encrypted so I leave that option off). Right now I do that via GNU screen. This works well, however, it would be nice to have a supported way to run just the daemon without the overhead of a curses application running in the background. 

For examples of how this is done elegantly you can look at [mocp](https://github.com/jonsafari/mocp) and [MPD + ncmpcpp](https://wiki.archlinux.org/index.php/Music_Player_Daemon) (or any other variety of clients to MPD).

For the curious, I have `signal` set up as an alias to the following command: `screen -d -R -S signal scli`, which will attach to an existing screen session under the name `signal` and create one if none exist.

**Comment by exquo** [comment]
Encrypted history would be great! I was thinking about suggesting it upstream (signal-cli). Maybe use something like gnome-keyring for easy decryption. 

Running a program like scli in the background while receiving desktop notifications, and bringing it to the foreground when needed would fit many people's usecases, I imagine. But resources-wise, the overhead created by curses / urwid is tiny compared to the resource consumption of, e.g. signal-cli's own java process. Creating a special mode to cut out just the urwid part would probably reduce the performance footprint by a negligible amount, but would require significant code changes.

If saving resources is not the main issue, then your current approach of putting scli into a GNU screen session looks like a good way to go, in line with the unix philosophy of combining tools for different jobs. It could have been even simpler if scli could simply run in the background with `scli &`, but after a quick try it seems like urwid's `main_loop` doesn't like that..

Finally, if you really want to forego curses, there are some barebone scripts on signal-cli's [wiki page](https://github.com/AsamK/signal-cli/wiki) that would just show the messages notifications. It should be pretty easy to extend them to also pipe the incoming message to a temporary (in-memory) file, so that you can have message history, but it wouldn't be saved on the disk unencrypted.

On Mon-16:00, Michael DiStefano wrote:
> I like running `scli` in the background to receive notifications and maintain a chat history (I know history can be preserved but it is not encrypted so I leave that option off). Right now I do that via GNU screen. This works well, however, it would be nice to have a supported way to run just the daemon without the overhead of a curses application running in the background. 
> 
> For examples of how this is done elegantly you can look at [mocp](https://github.com/jonsafari/mocp) and [MPD + ncmpcpp](https://wiki.archlinux.org/index.php/Music_Player_Daemon) (or any other variety of clients to MPD).
> 
> For the curious, I have `signal` set up as an alias to the following command: `screen -d -R -S signal scli`, which will attach to an existing screen session under the name `signal` and create one if none exist.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/isamert/scli/issues/75

-------------------------------------------------
This free account was provided by VFEmail.net - report spam to abuse@vfemail.net
 
ONLY AT VFEmail! - Use our Metadata Mitigator to keep your email out of the NSA's hands!
$24.95 ONETIME Lifetime accounts with Privacy Features!  
15GB disk! No bandwidth quotas!
Commercial and Bulk Mail Options!

**Comment by exquo** [comment]
An update and summary:

- For a discussion of encrypting the messages history, see [Data storage](https://github.com/isamert/scli#data-storage) in README.
- Adding a "no-curses" mode to `scli` is not really practical, nor would it really save on resources. 
- Simply putting `scli` in the background is better accomplished with other terminal tools, such as `screen`, etc.
