### ISSUE TITLE
single-sided mode in 0.2.0

### ISSUE THREAD

**Issue by bjohas** [isamert/scli#89]
Thank you for the recent update with message receipts - that's great!

For single-sided mode, the message receipts somehow interfere with the message text. The message receipts work, but the message text is not shown.

Many thanks!

**Comment by exquo** [comment]
Sure thing!

Strange, it seems to work fine for me with `--one-sided` or `--one-sided  --show-names` for both individual and group messages.. 

Could you describe the behavior in more detail (since I can't observe it myself). When you send a message, only its status checkmark is shown, but not the text itself? Or do you need to get a receipt (delivered / read) for the message's text to disappear? Do the messages *received* from others get shown normally (with `>>` in front)?

Maybe there's something else in your `~/.config/sclirc`? Also, could try running with `--debug` to see if there's any relevant output there?


On Sat-06:24, Bjoern wrote:
> Thank you for the recent update with message receipts - that's great!
> 
> For single-sided mode, the message receipts somehow interfere with the message text. The message receipts work, but the message text is not shown.
> 
> Many thanks!
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/isamert/scli/issues/89

-------------------------------------------------
This free account was provided by VFEmail.net - report spam to abuse@vfemail.net
 
ONLY AT VFEmail! - Use our Metadata Mitigator to keep your email out of the NSA's hands!
$24.95 ONETIME Lifetime accounts with Privacy Features!  
15GB disk! No bandwidth quotas!
Commercial and Bulk Mail Options!
