### ISSUE TITLE
Couldn't find any linked device

### ISSUE THREAD

**Issue by Ostropol** [isamert/scli#91]
Hello everyone!

I have the signal-cli daemon running, but whenever I run scli I get the error:
**Couldn't find any linked device.**

Does anyone know what that might be?
I can't seem to get it to work.

**Comment by exquo** [comment]
This happens when `scli` can't find your `signal-cli`'s data file. After `signal-cli` is registered / linked, the data file should be in

```
~/.local/share/signal-cli/+<YOUR_PHONE_NUMBER>
```

Another thing that shouldn't be relevant to this issue, but also: note that `signal-cli`'s daemon should not be running when launching `scli`: `scli` will start it itself. 



On Mon-15:04, Ostropol wrote:
> Hello everyone!
> 
> I have the signal-cli daemon running, but whenever I run scli I get the error:
> **Couldn't find any linked device.**
> 
> Does anyone know what that might be?
> I can't seem to get it to work.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/isamert/scli/issues/91

-------------------------------------------------
This free account was provided by VFEmail.net - report spam to abuse@vfemail.net
 
ONLY AT VFEmail! - Use our Metadata Mitigator to keep your email out of the NSA's hands!
$24.95 ONETIME Lifetime accounts with Privacy Features!  
15GB disk! No bandwidth quotas!
Commercial and Bulk Mail Options!

**Comment by Ostropol** [comment]
> This happens when `scli` can't find your `signal-cli`'s data file. After `signal-cli` is registered / linked, the data file should be in ``` ~/.local/share/signal-cli/+<YOUR_PHONE_NUMBER> ``` Another thing that shouldn't be relevant to this issue, but also: note that `signal-cli`'s daemon should not be running when launching `scli`: `scli` will start it itself.
> […](#)
> On Mon-15:04, Ostropol wrote: Hello everyone! I have the signal-cli daemon running, but whenever I run scli I get the error: **Couldn't find any linked device.** Does anyone know what that might be? I can't seem to get it to work. -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #91
> ------------------------------------------------- This free account was provided by VFEmail.net - report spam to abuse@vfemail.net ONLY AT VFEmail! - Use our Metadata Mitigator to keep your email out of the NSA's hands! $24.95 ONETIME Lifetime accounts with Privacy Features! 15GB disk! No bandwidth quotas! Commercial and Bulk Mail Options!

Hmm on my device there are three directories inside ~/.local/share/signal-cli/ which are: attachments, avatars and data. 
Naturally I've checked the 'data' directory and in there I can find my phone number. How do I go about changing this in the scli script? Is that even advisable? Also, how do I make sure scli is able to start the daemon? I have to manually type ./signal-cli inside it's data directory to get it to do anything. Did I mess something up there?

Thanks for your patience.

**Comment by Ostropol** [comment]
Actually, somehow it works now! I deleted the scli directory, cloned it again and ran it without first running the signal-cli daemon manually. I think that did the trick! Thanks a lot!

**Comment by exquo** [comment]
The directory structure you have described is the right one. I've missed the `data` dir in my comment above (sorry - wrote it from memory). 

You shouldn't need to do any extra steps at all, just run
```
scli
```
and it should just work. 

Starting the daemon manually is not necessary. (In fact, it shouldn't work at all - the daemon should refuse to start if there is a daemon running already, one started either manually or by scli).

The reason you get "send failed" messages might be because signal-cli daemon has not fully started yet (again, scli will start that daemon, it just takes a bit to get responsive). Wait a few seconds after starting scli before attempting to send a message, and it should work.

**Comment by exquo** [comment]
Closing because of no response. Please feel free to reopen / post any comments below.
