### ISSUE TITLE
Possible issues with new style groups

### ISSUE THREAD

**Issue by cycneuramus** [isamert/scli#95]
I've noticed some strange behaviours whenever I interact with a [new style group](https://signal.org/blog/new-groups/). Currently, only one of my group conversations have been upgraded to this new style. Now, I have noticed two issues with scli here:

1. Whenever I receive messages in this group conversation, scli shows the message as coming from the individual contact sending the message rather than from the group conversation itself.
2. As soon as I have received a message from this new group, scli effectively breaks, in the sense that if I quit out of scli and try to start it up again, it no longer works:

```
Traceback (most recent call last):  
  File "/usr/bin/scli", line 2485, in <module>  
    main()  
  File "/usr/bin/scli", line 2471, in main  
    state = State(ObservableConfig(cfg))  
  File "/usr/bin/scli", line 1795, in __init__  
    self.signal = Signal(cfg.username)  
  File "/usr/bin/scli", line 996, in __init__  
    self.reload()  
  File "/usr/bin/scli", line 1017, in reload  
    self.groups = [  
  File "/usr/bin/scli", line 1020, in <listcomp>  
    if g['name']  
KeyError: 'name'
```

scli version: 0.2.1
signal-cli version: 0.7.0

Possibly related: https://github.com/AsamK/signal-cli/issues/354

**Comment by exquo** [comment]
Yes, I'm getting the same problem with the new groups. I've pushed a commit to `master` to fix the startup issue, and a new minor release [v0.2.2](https://github.com/isamert/scli/releases/tag/v0.2.2).  

The V2 group messages appear as individual ones because signal-cli currently only shows the groupIds in its daemon's non-json mode (AsamK/signal-cli#386).

The crash had been caused by signal-cli not including V2 group names in its data file (AsamK/signal-cli#387), which scli assumed every group would have. 

The new group support in signal-cli is very fresh, so there are a few things remaining to be ironed out.

**Comment by cycneuramus** [comment]
That was fast, thank you. I can confirm the startup issue is gone on `0.2.2`.

**Comment by AckslD** [comment]
I'm having issues with groups as well. I'm very new to signal and this cli so not sure if my issue is related to this one. If not let me know if I should open a separate issue.

When doing `signal-cli -u xxx listGroups` I see my groups. However they do not show up in `scli`, even if I enable `--group-contacts`. Any idea what is going wrong?

Loving this cli btw, thanks for the great work :)

**Comment by exquo** [comment]
v2 groups support is now added to `master`. Please give it a try and I'll push it as a release in a few days.

On Sun-08:20, Axel Dahlberg wrote:
> I'm having issues with groups as well. I'm very new to signal and this cli so not sure if my issue is related to this one. If not let me know if I should open a separate issue.
> 
> When doing `signal-cli -u xxx listGroups` I see my groups. However they do not show up in `scli`, even if I enable `--group-contacts`. Any idea what is going wrong?
> 
> Loving this cli btw, thanks for the great work :)
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/isamert/scli/issues/95#issuecomment-757502271

-------------------------------------------------
This free account was provided by VFEmail.net - report spam to abuse@vfemail.net
 
ONLY AT VFEmail! - Use our Metadata Mitigator to keep your email out of the NSA's hands!
$24.95 ONETIME Lifetime accounts with Privacy Features!  
15GB disk! No bandwidth quotas!
Commercial and Bulk Mail Options!

**Comment by AckslD** [comment]
Awesome @exquo seems to work for me :)

**Comment by AckslD** [comment]
@exquo I just made a fresh install on a new computer and linked it. However, I again now don't see my group contacts. Did anything change lately? I'm on latest master.

**Comment by AckslD** [comment]
Maybe related to https://github.com/AsamK/signal-cli/issues/472, I'll see if it comes up when a message is sent.

**Comment by AckslD** [comment]
Indeed, when I got a message it said it's from `NULL`, then if I reload the group is there, although the message not.

**Comment by exquo** [comment]
Based on the issue you've referenced, it appears signal-cli does not add info about v2 groups to the data file until someone sends a message to the group. On the scli's end, the `NULL` message and the need to restart / manually reload contacts afterwards are caused by #71.

On Tue-02:12, Axel Dahlberg wrote:
> Indeed, when I got a message it said it's from `NULL`, then if I reload the group is there, although the message not.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/isamert/scli/issues/95#issuecomment-767441944

-------------------------------------------------
This free account was provided by VFEmail.net - report spam to abuse@vfemail.net
 
ONLY AT VFEmail! - Use our Metadata Mitigator to keep your email out of the NSA's hands!
$24.95 ONETIME Lifetime accounts with Privacy Features!  
15GB disk! No bandwidth quotas!
Commercial and Bulk Mail Options!

**Comment by AckslD** [comment]
Thanks for the info @exquo
